# Generated by Django 5.1.5 on 2026-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to='task_assets'),
        ),
    ]
