# Generated by Django 5.1.5 on 2026-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskdetails_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assets',
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='task_assets'),
        ),
    ]
