# Generated by Django 5.1.5 on 2026-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_taskdetails_assets_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='task_assets/default.jpg', upload_to='task_assets'),
        ),
    ]
